drop table user if exists;
create table user (
id bigint generated by default as identity comment '主键ID',
user_name varchar2(40) comment '登录名',
name varchar2(20) comment '用户名',
age int(3) comment '年龄',
balance decimal(10, 2) comment 'balance',
primary key (id)
);


