server:
  port: 8050

# spring-boot-actuator 配置
management:
  security:
    enabled: false # spring-boot-actuator 是否需要鉴权
endpoints:
  pause:
    enabled: true # 开启 actuator pause端点
  shutdown:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin$123@peer1:8760/eureka/,http://admin:admin$123@peer2:8761/eureka/ # 与eureka server交互地址
  instance:
    prefer-ip-address: true # true表示将该服务的ip注册到eureka server，
                            # 不配置或false则将服务所在系统hostname注册到eureka server
spring:
  application:
      name: consumer-gateway-zuul # 服务名称
zuul:
  ignored-services: discovery-eureka-ha,provider-user,consumer-hystrix-turbine #忽略代理服务
  routes:
    consumer-movie-ribbon-hystrix: /v1/movie/**  # 配置服务和路由路径映射
    consumer-movie-client-feign-hystrix: /v2/**
    service-sidecar: /sidecar/** # 路由 通过sidecar包装的其它服务或非JVM服务

# 大文件上传超时设置
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
