server:
  port: 8782

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/ # 与eureka server交互地址
  instance:
    prefer-ip-address: false # true表示将该服务的ip注册到eureka server，
                            # 不配置或false则将服务所在系统hostname注册到eureka server
spring:
  application:
      name: consumer-movie # 服务名称