drop table user if exists;
create table user (
id bigint generated by default as identity comment '主键ID',
user_name varchar2(40) comment '登录名',
name varchar2(20) comment '用户名',
age int(3) comment '年龄',
balance becimal(10, 2) comment 'balance',
primary key (id)
);

insert into user (id, user_name, name, age, balance)
values
(1, 'account1', '张三', 29, 80.00),
(2, 'lisi', '李四', 26, 89.12),
(3, 'wangwu', '王五', 29, 100.00);

