server:
  port: 8760
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将该服务注册到eureka server，默认true，
                                #当前服务就是一个eureka server，无需注册，设置为false
    fetch-registry: false #是否从eureka server获取注册信息，默认true，
                          #单点eureka server无需同步其它eureka的节点信息，设置为false
    server-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
